RedditOnRails/config/routes.rb
Rails.application.routes.draw do
  
  
  

  resources :users, only:[:new, :create]
  resource :session, only:[:new, :create, :destroy]
  resources :subs, except: [:destroy] do 
    resources :posts, only: [:new, :create]
  end 
  
  resources :posts, only:[:destroy, :edit, :update, :show] do
    resources :comments, only:[:create]
  end
  
  resources :comments, only:[:destroy]
  
  
end

RedditOnRails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RedditOnRails/app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, :user_id, :post_id, presence: true
  
  belongs_to :user
  
  belongs_to :post
  
  
  
  
end

RedditOnRails/app/models/post.rb
class Post < ApplicationRecord
  debugger
  validates :title, :content, presence:true
  validates :sub_ids, length: {minimum:1}
  
  has_many :comments
  has_many :postsubs, dependent: :destroy, inverse_of: :post
  has_many :subs, through: :postsubs, source: :sub 
  belongs_to :user
  
  
end

RedditOnRails/app/models/postsub.rb
class Postsub < ApplicationRecord
  validates :sub_id, uniqueness: {scope: :post_id}
  
  belongs_to :post
  
  belongs_to :sub
  
end 

RedditOnRails/app/models/sub.rb
class Sub < ApplicationRecord 
  
  validates :title, :description, presence:true
  
  has_many :postsubs, dependent: :destroy, inverse_of: :sub
  has_many :posts, through: :postsubs, source: :post
  
  belongs_to :moderator,
    foreign_key: :user_id,
    class_name: "User"
end 

RedditOnRails/app/models/user.rb
class User < ApplicationRecord
  after_initialize :ensure_session_token
  
  validates :password_digest, :username, :session_token, presence: true
  validates :username, :session_token, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil:true}
  
  attr_reader :password
  
  has_many :posts
  has_many :comments
  has_many :subs,
    foreign_key: :user_id,
    class_name: "Sub"
  
  
  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end
  
  def is_password?(pw)
    BCrypt::Password.new(self.password_digest).is_password?(pw)
  end
  
  def self.find_by_creds(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end
  
  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end
  
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
  
end

RedditOnRails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  
  def login(user)
    session[:session_token] = user.reset_session_token!
    @current_user = user
  end
  
  
  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end
  
  def logged_in?
    !!current_user
  end
  
  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end
  
  def require_login
    redirect_to new_session_url unless logged_in?
  end
  

  
  
end

RedditOnRails/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    comment = Comment.new(comment_params)
    comment.user_id = current_user.id
    comment.post_id = params[:post_id]
    comment.save
    flash[:errors] = comment.errors.full_messages
    redirect_to post_url(comment.post)
    
  end
  
  
  
  
  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to post_url(comment.post)
    
  end
  
  
  def comment_params
    params.require(:comment).permit(:content)
  end
  
  
end

RedditOnRails/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :require_login
  
  def new
    @post = Post.new
    @sub = Sub.find(params[:sub_id])
  end 
  
  def create 
    debugger
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    #@post.sub_id = params[:sub_id] 
    
    if @post.save
      redirect_to post_url(@post)
    else 
      flash.now[:errors] = ["Sub_ids #{post_params[:sub_ids]}"]       #@post.errors.full_messages 
      render :new 
    end 
  end 
  
  def show
    @post = Post.find(params[:id])
    # @sub = @post.subs.find(params[:id])
  end 
  
  def edit
    @post = current_user.posts.find(params[:id])
  end 
  
  def update 
    @post = current_user.posts.find(params[:id])
    
    if @post.update_attributes(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit 
    end 
  end 
  
  def post_params
    params.require(:post).permit(:title, :content, :url, sub_ids: [])
  end 
  
end 

RedditOnRails/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_creds(params[:user][:username], params[:user][:password])
    if @user
      login(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = ["wroong invalid something dude"]
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

RedditOnRails/app/controllers/subs_controller.rb
class SubsController < ApplicationController
    before_action :require_login
  
  def new
    @sub = Sub.new
  end 
  
  def create 
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id 
    
    if @sub.save
      redirect_to sub_url(@sub)
    else 
      flash[:errors] = @sub.errors.full_messages 
      render :new 
    end 
  end 
  
  def show
    @sub = Sub.find(params[:id])
  end 
  
  def index 
    @subs = Sub.all
  end 
  
  def edit
    @sub = current_user.subs.find(params[:id])
  end 
  
  def update 
    @sub = current_user.subs.find(params[:id])
    
    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit 
    end 
  end 
  
  def sub_params
    params.require(:sub).permit(:title, :description)
  end 
  
end 

RedditOnRails/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to subs_url 
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  def user_params
    params.require(:user).permit(:password, :username)
  end
  
end

RedditOnRails/app/helpers/application_helper.rb
module ApplicationHelper
end

RedditOnRails/app/helpers/sessions_helper.rb
module SessionsHelper
end

RedditOnRails/app/helpers/user_helper.rb
module UserHelper
end

RedditOnRails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditOnRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <% if logged_in? %>
      <%= current_user.username %>
      <form action="<%= session_url %>" method="post">
        <input type="hidden" name="_method" value="delete">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="submit" name="" value="Sign out">
      </form>
    <% else %>
      <a href="<%= new_session_url %>">Signing In</a>
      <a href="<%= new_user_url %>">SIGN UP</a>
    <% end %>
    
    <!-- <% if flash[:errors] %>
      <%  flash[:errors].each do |error| %>
        <%#= error %>
      <% end %>    
    <% end %>     -->
    
    <%= flash[:errors].join("<br>").html_safe if flash[:errors] %>
    
    <%= yield %>
  </body>
</html>

RedditOnRails/app/views/posts/edit.html.erb
<h1>Edit a Post</h1>


<form action="<%= edit_post_url(@sub) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>
    Title
    <input type="text" name="post[title]" value="<%= post.title %>">
  </label>
  <label>
    URL
    <input type="text" name="post[url]" value="<%= post.url %>">
  </label>
  <label>
    Content
    <input type="text" name="post[content]" value="<%= post.content %>">
  </label>
  
  <input type="submit" name="" value="Update the post">
</form>

RedditOnRails/app/views/posts/new.html.erb
<h1>Create a Post</h1>


<form action="<%= sub_posts_url(params[:sub_id]) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>
    Title
    <input type="text" name="post[title]" value="">
  </label>
  <br>
  <br>
  <label>
    URL
    <input type="text" name="post[url]" value="">
  </label>
  <br>
  <br>
  <label>
    Content
    <input type="text" name="post[content]" value="">
  </label>
  <br>
  <br>
    <label>Subs</label>
    <input type="hidden" name="post[sub_ids][]" value="">
    <% Sub.all.each do |sub| %>
    <br>
    <label> <%= sub.title %>
      <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>" <%= "checked" if @post.sub_ids.include?(sub.id) %> />
      </label>
      
    <% end %>
    <br>
    
    
  <input type="submit" name="" value="Create a post">
</form>

RedditOnRails/app/views/posts/show.html.erb
<h2><%= @post.title %></h2>

<br>

 URL: <a href="<%= @post.url %>"><%= @post.url %></a>
 <br>
 Content: <%= @post.content %>
 <br>
 <!-- Back to Sub Page: <a href="<%#= sub_url(@sub) %>">Sub</a> -->
 Back to All Subs <a href="<%= subs_url %>">All Subs</a>
 
 <br>
 
 <form action="<%= post_comments_url(@post) %>" method="post">
   <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
   <label>Add Comment
   <input type="text" name="comment[content]" value="">
   </label>
   <input type="submit" name="" value="Add Comment">   
 </form>
 
 
 <h1>Comments</h1>
 <ul>
   <% @post.comments.each do |comment| %>
   <li>
   <%= comment.content %>
   <form action="<%= comment_url(comment) %>" method="post">
     <input type="hidden" name="_method" value="delete">
     <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
     <input type="submit" name="" value="Delete COMMMENT">
   </form>
   </li>
   <% end %>
 </ul>

RedditOnRails/app/views/subs/edit.html.erb
<h1>Edit the sub</h1>


<form action="<%= edit_sub_url(@sub) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>
    Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>
  <label>
    Description
    <input type="text" name="sub[description]" value="<%= @sub.description %>">
  </label>
  <input type="submit" name="" value="Update SUB">
</form>

RedditOnRails/app/views/subs/index.html.erb
<h1>ALL THE SUBS</h1>


<a href="<%= new_sub_url %>">Create a new Sub</a>



<ul>
<% @subs.each do |sub| %>
<li>
  <a href="<%= sub_url(sub) %>"><%= sub.title %></a>
</li>
<% end %>
</ul>

RedditOnRails/app/views/subs/new.html.erb
<h1>Create a new sub</h1>


<form action="<%= subs_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>
    Title
    <input type="text" name="sub[title]" value="">
  </label>
  <label>
    Description
    <input type="text" name="sub[description]" value="">
  </label>
  <input type="submit" name="" value="Create a sub">
</form>

RedditOnRails/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

<h2>Description</h2>

<h3><%= @sub.description %></h3>

<a href="<%= new_sub_post_url(@sub) %>"> Make a new post </a>
<br>
<a href="<%= subs_url %>">All subs</a>

<ul>
  All Posts
  <% @sub.posts.each do |post| %>
    <li>    
      <a href="<%= post_url(post) %>">Test<%= post.title %></a>
    </li>
    <% end %>
</ul>

RedditOnRails/app/views/users/new.html.erb
<h1>SIGN UP 4 REDDIT</h1>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>
  Username
  <input type="text" name="user[username]" value="">
  </label>
  <label>
  Password
  <input type="text" name="user[password]" value="">
  </label>
  <input type="submit" name="" value="CREATE AN ACCOUNT">
</form>